### ISSUE TITLE
Undefined Index image_url in Ebizmarts\MailChimp\Model\Api\Product on line 299

### ISSUE THREAD

**Issue by simonrl** [mailchimp/mc-magento2#477] opened 2018-11-16 07:48 UTC
### Preconditions

1. Magento CE 2.1.14 with production data in production mode
2. mc-magento2 1.1.32
3. maybe relevant: we use configurable products, and some children are set to "Not visible individually", while some children are set to "Visible in Search".

### Steps to reproduce

You can see it in the code, explained below.
The error message occurs on cron run.

### Actual and Expected result

line 299 reads:
`$variendata["image_url"] = $data["image_url"];`

However, there are cases when `$data["image_url"]` is not set during `$this-> _buildProductData($product, $magentoStoreId);`, for example when neither the child nor parent product has an image.

We changed line 299 to:
`$variendata["image_url"] = !empty($data["image_url"]) ? $data["image_url"] : '';`

...as a hotfix, but this is not a sufficient solution imho. I would expect the configured placeholder to be used as the product image.

**Comment by simonrl** [comment] 2018-11-27 16:18
Could we get feedback on this please? Thanks!

**Comment by gonzaloebiz** [comment] 2018-11-28 15:10
Hi @simonrl 

i try defining a new configurable product without image, and some simple childrens all without  image, and define some childrens as visible and other as not visible, but i can't reproduce your issue. The products are synced without problem
How you define your products?

Best

**Comment by gonzaloebiz** [comment] 2018-12-10 15:35
close the issue until we have news

**Closed as completed by gonzaloebiz** 2018-12-10 15:35 UTC
Labels: need feedback

**Comment by daveblake** [comment] 2019-05-30 13:34
Hi,

We have also just experienced this error.

```
[Exception]
  Notice: Undefined index: image_url in /var/www/....../public_html/app/code/Ebizmarts/MailChimp/Model/Api/Product.php on line 311
```

We're also using a configurable product which doesn't have an image for any parents or child products.

Have spent a bit of time debugging the code and $this->_parentImage is never set.

**Comment by gonzaloebiz** [comment] 2019-05-30 16:08
Hi @daveblake 

if you have an issue with this, please open a new issue.

Best
