### ISSUE TITLE
Error with default config allows unassociated list to be attached to a store config.

### ISSUE THREAD

**Issue by cmsteadman** [mailchimp/mc-magento2#50] opened 2017-06-19 20:33 UTC
In MailChimp for Magento 2, a MailChimp store must be created before it can be selected for use in a store configuration. However, if default configuration is selected for list but not store when setting up a second store, this will return the following error:

`Something went wrong while saving this configuration: Notice: Undefined index: value in /var/www/html/magento/vendor/mailchimp/mc-magento2/Model/Config/Backend/MonkeyStore.php on line 85`

We should either clarify the error or remove the option of selecting a list within the MailChimp configuration and only allow list selection in the store creation step.

**Comment by ebizmarts-keller** [comment] 2017-08-15 17:27
Hello @cmsteadman 

This is supposed to be fixed in version 1.0.22 but let me know if this isn't the case, please make sure you are using this version of the module and if so, can you show me the content of the function **beforeSave** in vendor/mailchimp/mc-magento2/Model/Config/Backend/MonkeyStore.php ?

Thanks

**Closed** 2017-08-16 13:37 UTC
Labels: DONE

**Comment by epson121** [comment] 2017-09-01 06:57
Hi @ebizmarts-keller 

this has not been fixed in 1.0.22 yet. The issue is in `beforeSave` method, and AFAICT in line 88:

`$this->oldListId = $this->_helper->getConfigValue(\Ebizmarts\MailChimp\Helper\Data::XML_PATH_LIST, $this->getScopeId());`

should be changed to 

`$this->oldListId = $this->_helper->getConfigValue(\Ebizmarts\MailChimp\Helper\Data::XML_PATH_LIST, $this->getScopeCode());`

Is this the only change needed? Can you provide a patch for this bug?

**Comment by gonzaloebiz** [comment] 2017-09-01 12:04
This is already fixed and will be available in the next release.
Best
