### ISSUE TITLE
Magento sync not working with mailchimp

### ISSUE THREAD

**Issue by wildrness** [mailchimp/mc-magento2#548] opened 2018-12-28 16:28 UTC
Sync is not working

The sync (ebizmarts_ecommerce) does not sync

Issue Description

Preconditions

The sync not working for all entities

1. Magento CE 2.2.5
2. mc-magento2 1.0.31
Actual and Expected result

Expected result:
Data is synced with Mailchimp
Actual result:
Data is not synced with Mailchimp
Additional information

errors

 [] []
[2018-12-28 16:21:44] MailChimpLogger.INFO: API Key Invalid for Api Call: [https://us1.api.mailchimp.com/3.0/ecommerce/stores/MANYNUMBERSANDLETTERS] using method [GET]
	Detail: [Your API key may be invalid, or you've attempted to access the wrong datacenter.]

Note

I have used two different API strings, and mailchimp recognises the store, no data is passed.

**Comment by sucicf1** [comment] 2019-01-09 15:50
on magento ce 2.2.6. and mc-magento2 1.0.32 we have the same problem

**Comment by ThisIsRuddy** [comment] 2019-01-10 12:45
Hey @wildrness, I had a similar problem on 2.1 so I switched to the develop-2.1 branch and it fixed everything.

Are/have you tried the develop-2.2 branch?

**Comment by gonzaloebiz** [comment] 2019-01-10 15:23
This typically is an issue with the configuration, double check if you have any store with the extension enable but no mailchimp store assigned.
Any way the issue is fixed in the develop branch.

Best

**Closed as completed by gonzaloebiz** 2019-01-10 15:23 UTC

**Comment by sucicf1** [comment] 2019-01-10 15:59
i tried the develop branch and it didn't help
