### ISSUE TITLE
Product Images are broken in Abandoned cart emails

### ISSUE THREAD

**Issue by syzovao** [mailchimp/mc-magento2#169] opened 2017-12-29 18:31 UTC
### Preconditions

    1. Magento CE 2.1.9 without sample data is installed.
    2. mc-magento2 1.0.25.
    3. Test category is set up.
    4. Simple Product with image is created and assigned to the Test Category.
    5 In Mailchimp created Abandon cart Email Campaign with template where up to 2 products in cart. Use Maichimp standard block for template.

### Steps to reproduce

    1. Navigate to storefront as registered customer.
    2. Open Test Category.
    3. Click "Add to Cart" on the Simple Product.
    4. Open mini shopping cart and click "Proceed to Checkout".
    5. Abandon cart
    6. Wait till Abandoned cart emails is sent (it should be sent after one hour after customer abandons cart)
    7. Open email and pay attention to products images

###  Actual result 
Images are broken in Abandoned cart emails. 
Image contain additional "pub/" part in the URL:
Actual Image URL: http://sitename.com/pub/media/catalog/product/1/7/17st10551-bkwh_17sb30950-bkwh_431_front.jpg
Shoul be: http://sitename.com/media/catalog/product/1/7/17st10551-bkwh_17sb30950-bkwh_431_front.jpg
### Expected result
Images shown in email.

**Comment by gonzaloebiz** [comment] 2018-01-15 17:37
Hi @syzovao 

thanks for your feedback.
Why your images are in media/ and not in pub/media?
In a vanilla installation with nginx, you can view that the media directory is not a real one, is a rule in the nginx configuration file (see at https://github.com/magento/magento2/blob/2.1/nginx.conf.sample#L123-L143)
In other hand, you can check in your installation that the pub/media directory is a real directory and contain all the product images. As their name point, this is a public folder with some exceptions (you can see it at https://github.com/magento/magento2/blob/2.1/nginx.conf.sample#L82-L88)
So, will be interesting if you share more of your configuration (if you use apache or nginx, your apache/nginx configuration including .htaccess or some other special files, your base urls in magento and any other useful information)

Best

**Comment by syzovao** [comment] 2018-01-16 10:19
Hi @gonzaloebiz!

We have this issue on Staging Dev-qa Environment that is on Magento cloud. Dev-qa Environment is in production mode, so static files are automatically deployed.
Our images in pub/media. But Magento doesn't include pub/ in path for media or static files. Another example: js file in static/ not pub/static/.

This URL in email and it doesn't show image (real domain changed to http://example.magentosite.cloud/):
http://example.magentosite.cloud/pub/media/catalog/product/1/7/17st10551-bkwh_17sb30950-bkwh_431_front.jpg
http://example.magentosite.cloud/pub/media/catalog/product/cache/image/1000x1320/e9c3970ab036de70892d86c6d221abfe/1/7/17st10551-bkwh_17sb30950-bkwh_431_front.jpg

But image actually exists following this URLs:
http://example.magentosite.cloud/media/catalog/product/1/7/17st10551-bkwh_17sb30950-bkwh_431_front.jpg
http://example.magentosite.cloud/media/catalog/product/cache/image/1000x1320/e9c3970ab036de70892d86c6d221abfe/1/7/17st10551-bkwh_17sb30950-bkwh_431_front.jpg

More details please see in email.

**Comment by jcolas15** [comment] 2018-03-12 15:52
Hi is there any update on a fix for this issue? We are also experiencing the same thing

**Comment by rliukshyn** [comment] 2018-03-23 06:50
Hi @gonzaloebiz 
Are there any updates regarding this issue?
I experience it as well because DocumentRoot of my apache is magento_root/pub folder.
FYI, it is a common practice to set pub/ directory as a root on production environment because of security concerns. For example, if your docroot is magento_root folder and your server is not configured properly, you can open content of composer.json like this - http://magento.com/composer.json

**Comment by dmatthew** [comment] 2018-03-27 19:50
@syzovao and @gonzaloebiz - I believe this is a Magento bug: 
https://github.com/magento/magento2/issues/9111
https://github.com/magento/magento2/issues/8868

**Comment by damodamo** [comment] 2018-03-31 07:59
I am experiencing the same issue.
I have a 100% Standard/Vanilla Magento 2.2 installation and have just integrated with MailChimp.
Product images were uploaded using the standard Magento click and upload process.

Magneto displays all images correctly, so I assume this is a bug with MailChimp integration.

Any thoughts on the source of the bug or fix date?

Also, **ONE BIG ISSUE**, why does the MailChimp Abandoned cart feature **only work with signed in customers**? 95% will not sign-in before the checkout page, making this feature almost not worth the effort to install.

**Comment by gonzaloebiz** [comment] 2018-04-02 16:27
Hi @dmatthew 

you are right, the issue is from magento, not from our extension.
The extension use a magento function to retrieve the media url (take a look at https://github.com/mailchimp/mc-magento2/blob/develop/Model/Api/Product.php#L354 and https://github.com/mailchimp/mc-magento2/blob/develop/Helper/Data.php#L511), but this return something like pub/media and not media/
For a workaround take a look at https://github.com/magento/magento2/issues/9111#issuecomment-292002922

@damodamo 

The extension syncs not only the signed customer, also the guest customer that already put their email in the checkout (without an email address we don't send any email)

Best

**Closed as completed by gonzaloebiz** 2018-04-02 16:27 UTC

**Comment by damodamo** [comment] 2018-04-02 16:35
@gonzaloebiz Many thanks for the information.

Regarding the MailChimp extension also working for Guest customers, our testing shows this may not be the case. Can anyone else confirm this functionality is working as stated?

Many thanks.

**Comment by consultblu** [comment] 2018-07-17 17:57
@gonzaloebiz Respectfully you are wrong.  Althought the physical image file can be found in "pub/media/catalog/product/*/*" magento does not allow you to access those original files directly.

Magento allows admins to configure where they want to allow access to these images here:
Magento Admin > Stores > Configuration > General [tab] > Web > Base URL for User Media Files => "{{unsecure_base_url}}media/"
Magento Admin > Stores > Configuration > General [tab] > Web > Secure Base URL for User Media Files => "{{secure_base_url}}media/"

Magento Database > core_config_data [Table]:
Path: web/unsecure/base_media_url
Path: web/secure/base_media_url

Just Use \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig, In your constructor argument and set the class property: $this->scopeConfig = $scopeConfig;

Now to Get the configuration value just use

$this->scopeConfig->getValue('web/unsecure/base_media_url', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);

OR

$this->scopeConfig->getValue('web/secure/base_media_url', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);

If I configure my site with "{{secure_base_url}}media/" then my media url will then look like this: https://www.somewebsite.com/media/catalog/product/b/b/bbq_chips.jpg

and not this:
https://www.somewebsite.com/pub/media/catalog/product/b/b/bbq_chips.jpg

**Comment by gonzaloebiz** [comment] 2018-07-17 18:17
Hi @consultblu 

you already see [at this?](https://github.com/magento/magento2/issues/9111#issuecomment-292002922)

**Comment by consultblu** [comment] 2018-07-17 18:49
Looking at it and found that they moved it here: <a href="https://github.com/magento/magento2/issues/8868">here</a>

Many users on that thread report that following works for accessing the images.
{{unsecure_base_url}}media/
{{secure_base_url}}media/

I'm asking you to reference this data so that your plugin can work.

**Comment by gonzaloebiz** [comment] 2018-07-17 19:01
The extension don't need to manage these values, the magento libraries do it (see the comment on Apr 2)
Changing the values of Base URL for User Media Files and Secure Base URL for User Media Files in the admin fix the issue

Best

**Comment by consultblu** [comment] 2018-07-17 19:35
Nowhere in my comments have I asked you [the mailchimp plugin] to manage these values.  I have asked you to use them instead of relying on a variable that is shown to have errors.

With regard to changing the forementioned values; I have done that, reindexed my products, and reconnected my site 3 times now. Mailchimp still has the incorrect image urls.

The mailchimp feature still does not work. 

I have presented a updated to the plugin where your mailchimp customers can user your service and not wait until a new version of magento [2.3 or 2.4] is released.

**Comment by gonzaloebiz** [comment] 2018-07-17 19:49
What do you mean with "reconnect my site"? 
The easy way is
- create a new MailChimp store
- change the associated MailChimp store
- wait until resync

If you simply change these values is not enough, the products are already synced and must be re synced

**Comment by iamgeert** [comment] 2018-11-05 01:20
> Nowhere in my comments have I asked you [the mailchimp plugin] to manage these values. I have asked you to use them instead of relying on a variable that is shown to have errors.
> 
> With regard to changing the forementioned values; I have done that, reindexed my products, and reconnected my site 3 times now. Mailchimp still has the incorrect image urls.
> 
> The mailchimp feature still does not work.
> 
> I have presented a updated to the plugin where your mailchimp customers can user your service and not wait until a new version of magento [2.3 or 2.4] is released.

Adding a rewrite rule to your nginx configuration might solve the issue:
rewrite ^/pub(.*)$ $1 last;

**Comment by lstellway** [comment] 2018-11-22 01:22
Hmm .. we are trying to implement product recommendations within a MailChimp email and I'm seeing many of the product images are broken. I believe I will need to re-sync with a new MailChimp store.

--

Regarding the images issue, I just use a symbolic link in the `pub` directory. You can run the following command from within the directory:
```
ln -s ./ pub
```
