### ISSUE TITLE
Products with custom options that have price does not enter mailchimp

### ISSUE THREAD

**Issue by mohammedTBB** [mailchimp/mc-magento2#1423] opened 2022-06-13 15:01 UTC
**Issue Description**
the orders that hace a product with custom option that have price does not sent to mailchimp,
while the option is free the order enter to mailcihmp normally 

**Preconditions**
-Magento 2.4.3
-Php 7.4
-mailchimp/mc-magento2 103.4.44

**Steps to reproduce**
1. create a simple product
2. add new customizable option with price (in product page admin store)
3. make an order buying this product with the customizable option selected

Actual
the order does not sync with mailchimp

**Expected**
the order sync normally

**Pssible related issue:**
1421

**Comment by federicocanedo** [comment] 2022-06-13 17:53
Hello again Mohammed,

I tried recreating this issue and wasn't able to get the same result as you.

After making an order **without** the custom option selected the order didn't get to MailChimp as MailChimp won't take orders with price 0.

But after selection the option the order went through and I could see it registered on the MailChimp site.
![image](https://user-images.githubusercontent.com/102973963/173414080-5c0c33ce-e9fa-4b89-a8b6-1a7107094b3d.png)
![image](https://user-images.githubusercontent.com/102973963/173414145-ef1ab98a-4194-4e00-a4a0-4a78db393643.png)

If you had tested something different to what've done you can tell me the steps to reproduce so I can test the function.

**Comment by mohammedTBB** [comment] 2022-06-14 07:52
Hi @federicocanedo 

sorry I forgot to mention that the order should be made through an abandoned cart.

the purchase is attributed to Mailchimp in the Magento order panel, however, the information on the sale made and the revenue obtained is not entered in Mailchimp.

**Comment by federicocanedo** [comment] 2022-06-16 18:12
Having the same result again

![image](https://user-images.githubusercontent.com/102973963/174135653-aabad099-a8e7-4276-b272-b65951c972db.png)

Does the custom option and the product have a price of 0 in your tests?
If the total price is 0 it won't be supported by mailchimp, in this case there is not much we can do.

**Comment by mohammedTBB** [comment] 2022-06-17 07:01
The product have price 0, but the option have a price.

ths issuse actually that the order dose not appear in ecommerce->order history

![Captura de pantalla -2022-06-17 08-57-50 (1)](https://user-images.githubusercontent.com/66772877/174243636-a55277b8-b91f-4738-a6e7-37861922ea65.png)


can we check that please?

**Comment by federicocanedo** [comment] 2023-05-04 12:03
This is not possible since Mailchimp does not support custom options, the alternative would be to create a need product for each variant.

At this moment we are not planning to implement this.

**Closed as not planned by federicocanedo** 2023-05-04 12:03 UTC
Labels: checking
