### ISSUE TITLE
Resource Not Found: The requested resource could not be found

### ISSUE THREAD

**Issue by crtl** [mailchimp/mc-magento2#358] opened 2018-08-01 11:23 UTC
## Issue Description
When running the ebizmarts_ecommerce job the following error is ocurring:
`Resource Not Found : The requested resource could not be found.`

It is related to line 228 in ebizmarts/mailchimp-lib/src/Mailchimp.php

### Preconditions

    1. Magento CE 2.2.4
    2. mc-magento2 1.0.29.

### Steps to reproduce

Run the magento cronjob

**Comment by gonzaloebiz** [comment] 2018-08-01 13:49
Hi @crtl 

thanks for your feedback.
We can't reproduce your issue with this data, we close the issue until we have more data to reproduce it.

Best

**Comment by crtl** [comment] 2018-08-01 14:29
Then could you please get into the habit of providing actual information when throwing exceptions instead of messages like "Things dont work".

**Comment by crtl** [comment] 2018-08-06 08:27
Ive got more output after altering some code, I have now the following information:

`curl_info($ch)`

```json
{
	"url": "https:\/\/us12.api.mailchimp.com\/3.0\/ecommerce\/stores\/3679d8bb2ee63bc941dc201122357d9a\/promo-rules\/13\/promo-codes",
	"content_type": "application\/problem+json; charset=utf-8",
	"http_code": 404,
	"header_size": 519,
	"request_size": 293,
	"filetime": -1,
	"ssl_verify_result": 0,
	"redirect_count": 0,
	"total_time": 0.155376,
	"namelookup_time": 2.7e-5,
	"connect_time": 2.9e-5,
	"pretransfer_time": 0.00011,
	"size_upload": 0,
	"size_download": 234,
	"speed_download": 1506,
	"speed_upload": 0,
	"download_content_length": 234,
	"upload_content_length": 0,
	"starttransfer_time": 0.15533,
	"redirect_time": 0,
	"redirect_url": "",
	"primary_ip": "104.87.223.21",
	"certinfo": [],
	"primary_port": 443,
	"local_ip": "10.0.2.15",
	"local_port": 48750
}
```

Response:

```json
{
	"type": "http:\/\/developer.mailchimp.com\/documentation\/mailchimp\/guides\/error-glossary\/",
	"title": "Resource Not Found",
	"status": 404,
	"detail": "The requested resource could not be found.",
	"instance": "21a49251-81d4-4e55-9d1a-c2029f58e2db"
}
```

**Comment by gonzaloebiz** [comment] 2018-08-06 14:00
Can you please share the definition of the price rule with id 13?

**Comment by crtl** [comment] 2018-08-08 10:35
What price rule do you mean?
We havent created any price rules in mailchimp.
Before seeing the erro details I didnt even know smth. like this existed.

**Comment by gonzaloebiz** [comment] 2018-08-08 12:21
Hi @crtl 

not in MailChimp, in magento. See the prices rules in magento and see for that with id 13

**Comment by crtl** [comment] 2018-08-08 13:07
I have no `Cart Price Rule` nor any `Catalog Price Rule` with an id of `13`.
Ive also looked in the database and couldnt find any artifacts.
When going to the `Catalog Price Rule` Page I had the warnings that I have to `Apply Rules` because of updates issued but there werent any rules listed.
Ive applied rules which took a relative long time and will now see if the issue got resolved.

**Comment by crtl** [comment] 2018-08-13 08:32
The Issue still persists.

**Comment by jonpday** [comment] 2018-08-17 11:32
@crtl can you please advise how you were able to get the extra debug info? did you edit a particular file in the Mailchimp module?

**Comment by crtl** [comment] 2018-08-17 11:35
Ive directily edited ebizmarts/mailchimp-lib/src/Mailchimp.php on around line 226

**Comment by gonzaloebiz** [comment] 2018-08-23 18:36
Update the ebizmarts/mailchimp-lib to the last version

Best

**Closed as completed by gonzaloebiz** 2018-08-23 18:36 UTC
Labels: need feedback

**Comment by vrajeshpatelklizer** [comment] 2025-07-07 08:29
> Ive directily edited ebizmarts/mailchimp-lib/src/Mailchimp.php on around line 226

Hi 

Can you share the exact information what you update ?
